# Generated by Django 5.1.7 on 2025-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
